/* SPDX-License-Identifier: AGPL-3.0-or-later */
window.PASTA_I18N = (() => {
  const en = {
    source:"Source", language:"Language", kicker:"THE NOODLE ORACLE REWRITES BYTECODE",
    title:"Turn legacy Bukkit plugins into Folia-aware artifacts.",
    lead:"Scheduler calls, BukkitRunnable, entity teleportation, and region-owned block writes are rewritten inside your browser. Every change is verified and documented.",
    trustLocal:"100% local", trustNoExec:"No plugin execution", trustReport:"Full audit report",
    ritual:"TRANSMUTATION RITUAL", uploadTitle:"Offer a plugin JAR to the machine god.",
    uploadHint:"Drop a Bukkit or Paper plugin. The original file remains untouched.",
    dropPrimary:"Drop plugin.jar here", dropSecondary:"or click to select a file · maximum 200 MB",
    privacy:"JAR bytes never leave this device.", engine:"ENGINE MATRIX",
    engineTitle:"Conservative where semantics matter. Aggressive where offsets stay stable.",
    engineScheduler:"Scheduler bridge", engineSchedulerBody:"Legacy scheduler calls → Folia global or async scheduler",
    engineRegion:"Region ownership", engineRegionBody:"Block mutations → location-bound RegionScheduler",
    engineEntity:"Entity migration", engineEntityBody:"Discarded teleport results → teleportAsync bridge",
    engineRefusal:"Semantic refusal", engineRefusalBody:"Used task handles and ambiguous APIs remain manual",
    verdict:"ORACLE VERDICT", compatibilityScore:"Compatibility score", pluginIdentity:"PLUGIN IDENTITY",
    version:"Version", mainClass:"Main class", apiVersion:"API", classes:"Classes", patched:"Patched sites",
    manual:"Manual findings", nested:"Nested JARs", signatures:"Signatures removed", elapsed:"Elapsed",
    downloadJar:"Download patched JAR", another:"Judge another JAR", audit:"TRANSFORMATION AUDIT",
    auditTitle:"Every rewritten and refused call site", filterAll:"All", filterPatched:"Patched", filterManual:"Manual",
    findingLimit:"The on-screen list is limited. Download the report for every call site.",
    warningTitle:"Runtime verification still matters.",
    warning:"Automatic transformation cannot prove region correctness for every execution path. Test the generated JAR on a disposable Folia server before production.",
    principle1Title:"Offset-stable bytecode", principle1Body:"Invoke instructions are replaced without shifting branch targets or exception tables.",
    principle2Title:"Injected runtime bridge", principle2Body:"A compact Java 17 bridge routes calls to Folia APIs with Paper fallback behavior.",
    principle3Title:"Auditable output", principle3Body:"The patched JAR contains META-INF/pasta-report.json and downloadable human-readable reports.",
    footer:"Independent project inspired by MARVserver/pasta and FoliaCode. Not affiliated with Mojang Studios or PaperMC.",
    preparing:"Preparing the offering…", opening:"Opening archive", scanning:"Parsing Java class files", transforming:"Rewriting call sites",
    packing:"Sealing transformed JAR", done:"Transformation complete", invalidJar:"The selected file is not a readable JAR archive.",
    tooLarge:"The JAR exceeds 200 MB.", workerError:"The bytecode engine stopped unexpectedly.", cleanTitle:"The plugin has been transmuted.",
    partialTitle:"The plugin was partially transmuted.", blockedTitle:"The oracle requires manual intervention.",
    cleanSummary:"All supported call sites were rewritten and no blocking Folia finding remains. Runtime testing is still required.",
    partialSummary:"Safe call sites were rewritten, but unresolved APIs remain. The output is intentionally not marked folia-supported.",
    blockedSummary:"No safe output could be produced. Review the report and modify the plugin source.",
    cleanBadge:"PATCHED", partialBadge:"PARTIAL", blockedBadge:"MANUAL", noFindings:"No transformation findings.",
    patchedLabel:"PATCHED", manualLabel:"MANUAL", scoreClean:"No known blocking call sites remain.",
    scorePartial:"Manual migration is still required.", scoreBlocked:"The archive could not be transformed safely.",
    unknownPlugin:"Unknown plugin"
  };

  const translations = {
    en,
    ja:{...en,source:"ソース",language:"言語",kicker:"麺の神託がバイトコードを書き換える",title:"旧式BukkitプラグインをFolia対応成果物へ。",lead:"スケジューラ、BukkitRunnable、エンティティ転送、リージョン所有ブロック操作をブラウザ内で書き換え、全変更を検証・記録します。",trustLocal:"完全ローカル",trustNoExec:"プラグインを実行しない",trustReport:"完全監査レポート",ritual:"変換の儀式",uploadTitle:"プラグインJARを機械神へ捧げる。",uploadHint:"Bukkit / Paperプラグインを投入してください。元ファイルは変更されません。",dropPrimary:"plugin.jar をここにドロップ",dropSecondary:"またはクリックして選択 · 最大200MB",privacy:"JARデータは端末外へ送信されません。",engine:"変換エンジン",engineTitle:"意味が変わる箇所は保守的に。オフセットを維持できる箇所は積極的に。",engineScheduler:"スケジューラ橋渡し",engineSchedulerBody:"旧式スケジューラ → Folia Global / Async Scheduler",engineRegion:"リージョン所有権",engineRegionBody:"ブロック変更 → 座標に紐づくRegionScheduler",engineEntity:"エンティティ移行",engineEntityBody:"未使用teleport結果 → teleportAsync橋渡し",engineRefusal:"意味論的拒否",engineRefusalBody:"使用中タスクハンドルや曖昧APIは手動対応",verdict:"神託の判定",compatibilityScore:"互換性スコア",pluginIdentity:"プラグイン情報",version:"バージョン",mainClass:"メインクラス",apiVersion:"API",classes:"クラス",patched:"書換箇所",manual:"手動対応",nested:"内包JAR",signatures:"削除署名",elapsed:"処理時間",downloadJar:"パッチ済みJARを保存",another:"別のJARを判定",audit:"変換監査",auditTitle:"書き換え・拒否された全呼び出し箇所",filterAll:"すべて",filterPatched:"書換済み",filterManual:"手動",findingLimit:"画面表示は一部です。全件はレポートを保存してください。",warningTitle:"実環境検証は必須です。",warning:"自動変換だけでは全実行経路のリージョン正当性を証明できません。本番前に使い捨てFoliaサーバーで検証してください。",principle1Title:"オフセット不変バイトコード",principle1Body:"分岐先や例外テーブルを移動せずinvoke命令を置換します。",principle2Title:"ランタイム橋渡しを注入",principle2Body:"Java 17の小型ブリッジがFolia APIへ振り分け、Paperでは従来動作へ戻します。",principle3Title:"監査可能な出力",principle3Body:"生成JARにMETA-INF/pasta-report.jsonを同梱し、人間向けレポートも保存できます。",footer:"MARVserver/pastaとFoliaCodeを参考にした独立プロジェクトです。Mojang Studios / PaperMCとは無関係です。",preparing:"供物を準備中…",opening:"アーカイブを展開",scanning:"Javaクラスを解析",transforming:"呼び出し箇所を書換",packing:"変換JARを封印",done:"変換完了",invalidJar:"読み取り可能なJARではありません。",tooLarge:"JARが200MBを超えています。",workerError:"バイトコードエンジンが異常終了しました。",cleanTitle:"プラグインの変換が完了した。",partialTitle:"プラグインを部分変換した。",blockedTitle:"神託は手動修正を要求した。",cleanSummary:"対応可能な呼び出しをすべて書き換え、既知の阻害項目は残っていません。実環境テストは必要です。",partialSummary:"安全な箇所は書き換えましたが未解決APIが残ります。出力にはfolia-supportedを付与しません。",blockedSummary:"安全な出力を生成できませんでした。レポートを確認しソースを修正してください。",cleanBadge:"変換済み",partialBadge:"部分変換",blockedBadge:"手動対応",noFindings:"検出項目はありません。",patchedLabel:"書換済み",manualLabel:"手動",scoreClean:"既知の阻害呼び出しは残っていません。",scorePartial:"手動移行が残っています。",scoreBlocked:"安全に変換できませんでした。",unknownPlugin:"不明なプラグイン"},
    de:{...en,source:"Quellcode",language:"Sprache",kicker:"DAS NUDELORAKEL SCHREIBT BYTECODE UM",title:"Alte Bukkit-Plugins in Folia-fähige Artefakte verwandeln.",lead:"Scheduler-Aufrufe, BukkitRunnable, Teleports und regionsgebundene Blockzugriffe werden lokal umgeschrieben, geprüft und protokolliert.",trustLocal:"100 % lokal",trustNoExec:"Keine Plugin-Ausführung",trustReport:"Vollständiger Prüfbericht",ritual:"TRANSMUTATION",uploadTitle:"Opfere dem Maschinengott eine Plugin-JAR.",uploadHint:"Bukkit- oder Paper-Plugin ablegen. Die Originaldatei bleibt unverändert.",dropPrimary:"plugin.jar hier ablegen",dropSecondary:"oder auswählen · maximal 200 MB",privacy:"JAR-Daten verlassen dieses Gerät nicht.",verdict:"URTEIL",compatibilityScore:"Kompatibilitätswert",pluginIdentity:"PLUGIN-DATEN",version:"Version",mainClass:"Hauptklasse",classes:"Klassen",patched:"Gepatchte Stellen",manual:"Manuelle Befunde",nested:"Eingebettete JARs",signatures:"Entfernte Signaturen",elapsed:"Dauer",downloadJar:"Gepatchte JAR laden",another:"Weitere JAR prüfen",audit:"TRANSFORMATIONSBERICHT",auditTitle:"Alle geänderten und abgelehnten Aufrufstellen",filterAll:"Alle",filterPatched:"Gepatcht",filterManual:"Manuell",warningTitle:"Laufzeitprüfung bleibt erforderlich.",cleanTitle:"Das Plugin wurde transformiert.",partialTitle:"Das Plugin wurde teilweise transformiert.",blockedTitle:"Manuelle Arbeit erforderlich.",cleanBadge:"GEPATCHT",partialBadge:"TEILWEISE",blockedBadge:"MANUELL"},
    "zh-TW":{...en,source:"原始碼",language:"語言",kicker:"麵條神諭正在重寫位元組碼",title:"將舊版 Bukkit 外掛轉化為 Folia 相容成品。",lead:"排程器、BukkitRunnable、實體傳送與區域方塊寫入都在瀏覽器內重寫、驗證並記錄。",trustLocal:"完全本機",trustNoExec:"不執行外掛",trustReport:"完整稽核報告",ritual:"轉化儀式",uploadTitle:"將外掛 JAR 獻給機械之神。",uploadHint:"拖放 Bukkit 或 Paper 外掛，原始檔不會被修改。",dropPrimary:"將 plugin.jar 拖到這裡",dropSecondary:"或點擊選擇 · 最大 200 MB",privacy:"JAR 資料不會離開此裝置。",verdict:"神諭判定",compatibilityScore:"相容性分數",pluginIdentity:"外掛資訊",version:"版本",mainClass:"主類別",classes:"類別",patched:"已修補位置",manual:"手動項目",nested:"內嵌 JAR",signatures:"已移除簽章",elapsed:"耗時",downloadJar:"下載修補後 JAR",another:"判定另一個 JAR",audit:"轉化稽核",auditTitle:"所有重寫與拒絕的呼叫位置",filterAll:"全部",filterPatched:"已修補",filterManual:"手動",warningTitle:"仍需執行環境驗證。",cleanTitle:"外掛轉化完成。",partialTitle:"外掛已部分轉化。",blockedTitle:"神諭要求手動處理。",cleanBadge:"已修補",partialBadge:"部分",blockedBadge:"手動"},
    "zh-CN":{...en,source:"源代码",language:"语言",kicker:"面条神谕正在重写字节码",title:"将旧版 Bukkit 插件转化为 Folia 兼容产物。",lead:"调度器、BukkitRunnable、实体传送与区域方块写入均在浏览器内重写、验证并记录。",trustLocal:"完全本地",trustNoExec:"不执行插件",trustReport:"完整审计报告",ritual:"转化仪式",uploadTitle:"将插件 JAR 献给机械之神。",uploadHint:"拖放 Bukkit 或 Paper 插件，原文件不会改变。",dropPrimary:"将 plugin.jar 拖到这里",dropSecondary:"或点击选择 · 最大 200 MB",privacy:"JAR 数据不会离开此设备。",verdict:"神谕判定",compatibilityScore:"兼容性评分",pluginIdentity:"插件信息",version:"版本",mainClass:"主类",classes:"类",patched:"已修补位置",manual:"手动项目",nested:"内嵌 JAR",signatures:"已移除签名",elapsed:"耗时",downloadJar:"下载修补后的 JAR",another:"判定另一个 JAR",audit:"转化审计",auditTitle:"所有重写与拒绝的调用位置",filterAll:"全部",filterPatched:"已修补",filterManual:"手动",warningTitle:"仍需运行时验证。",cleanTitle:"插件转化完成。",partialTitle:"插件已部分转化。",blockedTitle:"神谕要求手动处理。",cleanBadge:"已修补",partialBadge:"部分",blockedBadge:"手动"},
    it:{...en,source:"Sorgente",language:"Lingua",kicker:"L'ORACOLO DELLA PASTA RISCRIVE IL BYTECODE",title:"Trasforma i vecchi plugin Bukkit in artefatti compatibili con Folia.",lead:"Scheduler, BukkitRunnable, teletrasporti e scritture regionali vengono riscritti localmente, verificati e documentati.",trustLocal:"100% locale",trustNoExec:"Nessuna esecuzione",trustReport:"Rapporto completo",ritual:"RITO DI TRASMUTAZIONE",uploadTitle:"Offri un JAR al dio macchina.",uploadHint:"Trascina un plugin Bukkit o Paper. L'originale resta intatto.",dropPrimary:"Rilascia plugin.jar qui",dropSecondary:"oppure seleziona · massimo 200 MB",privacy:"I dati JAR non lasciano il dispositivo.",verdict:"VERDETTO",compatibilityScore:"Punteggio compatibilità",pluginIdentity:"IDENTITÀ PLUGIN",version:"Versione",mainClass:"Classe principale",classes:"Classi",patched:"Siti modificati",manual:"Rilevamenti manuali",nested:"JAR annidati",signatures:"Firme rimosse",elapsed:"Durata",downloadJar:"Scarica JAR modificato",another:"Analizza un altro JAR",audit:"AUDIT DELLA TRASFORMAZIONE",auditTitle:"Ogni chiamata riscritta o rifiutata",filterAll:"Tutti",filterPatched:"Modificati",filterManual:"Manuali",warningTitle:"La verifica runtime resta necessaria.",cleanTitle:"Plugin trasformato.",partialTitle:"Plugin trasformato parzialmente.",blockedTitle:"Intervento manuale richiesto.",cleanBadge:"MODIFICATO",partialBadge:"PARZIALE",blockedBadge:"MANUALE"},
    es:{...en,source:"Código",language:"Idioma",kicker:"EL ORÁCULO DE PASTA REESCRIBE BYTECODE",title:"Convierte plugins Bukkit antiguos en artefactos compatibles con Folia.",lead:"Scheduler, BukkitRunnable, teletransportes y escrituras regionales se reescriben localmente, se verifican y se documentan.",trustLocal:"100% local",trustNoExec:"Sin ejecutar plugins",trustReport:"Informe completo",ritual:"RITUAL DE TRANSMUTACIÓN",uploadTitle:"Ofrece un JAR al dios máquina.",uploadHint:"Arrastra un plugin Bukkit o Paper. El original no se modifica.",dropPrimary:"Suelta plugin.jar aquí",dropSecondary:"o selecciona · máximo 200 MB",privacy:"Los datos JAR no salen del dispositivo.",verdict:"VEREDICTO",compatibilityScore:"Puntuación de compatibilidad",pluginIdentity:"IDENTIDAD DEL PLUGIN",version:"Versión",mainClass:"Clase principal",classes:"Clases",patched:"Sitios parcheados",manual:"Hallazgos manuales",nested:"JAR anidados",signatures:"Firmas eliminadas",elapsed:"Tiempo",downloadJar:"Descargar JAR parcheado",another:"Analizar otro JAR",audit:"AUDITORÍA DE TRANSFORMACIÓN",auditTitle:"Cada llamada reescrita o rechazada",filterAll:"Todos",filterPatched:"Parcheados",filterManual:"Manuales",warningTitle:"La verificación en ejecución sigue siendo necesaria.",cleanTitle:"Plugin transformado.",partialTitle:"Plugin transformado parcialmente.",blockedTitle:"Se requiere intervención manual.",cleanBadge:"PARCHEADO",partialBadge:"PARCIAL",blockedBadge:"MANUAL"}
  };

  return translations;
})();
